services:

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: yosbelm/tukiosko:backend
    container_name: tukiosko_backend

    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"

    command: gunicorn tuKiosko.wsgi:application --bind 0.0.0.0:8000


  frontend:
    build:
      context: ./frontend/tukiosko
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/api/v1/
    image: yosbelm/tukiosko:frontend
    container_name: tukiosko_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: