FROM node:22-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_API_BASE_URL="http://localhost:8000/api/v1/"
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

EXPOSE 80

CMD ["npm", "run", "dev", "--", "--host"]