# Generated by Django 6.0.3 on 2026-03-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='orden',
        ),
        migrations.CreateModel(
            name='ProductoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_producto_vendido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_producto_vendido', to='tuKioskoApp.producto')),
                ('venta_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuKioskoApp.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_model', to='tuKioskoApp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='orden',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_producto_ordenado', to='tuKioskoApp.vendedor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedor_venta', to='tuKioskoApp.vendedor'),
        ),
    ]
