# Generated by Django 6.0.3 on 2026-03-27 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0002_remove_venta_orden_productovendido_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to='tuKioskoApp.usuario'),
        ),
    ]
