# Generated by Django 6.0.3 on 2026-03-27 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0003_alter_vendedor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=20),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='salario',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
