# Generated by Django 6.0.3 on 2026-03-31 21:03

from django.db import migrations

def crear_area_kiosko(apps, schema_editor):
    # Obtenemos el modelo histórico
    Area = apps.get_model('tuKioskoApp', 'Area')
    
    # get_or_create busca un registro con nombre='kiosko'. 
    # Si no lo encuentra, lo crea. Si ya existe, no hace nada.
    Area.objects.get_or_create(nombre='kiosko')

# 2. Función para revertir el dato (opcional pero recomendada)
def revertir_area_kiosko(apps, schema_editor):
    Area = apps.get_model('tuKioskoApp', 'Area')
    # Si revertimos la migración, borramos el área
    Area.objects.filter(nombre='kiosko').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0005_alter_usuario_email_alter_usuario_groups_and_more'),
    ]

    operations = [
        migrations.RunPython(crear_area_kiosko, revertir_area_kiosko),
    ]
