# Generated by Django 6.0.3 on 2026-03-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0006_auto_20260331_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
