# Generated by Django 6.0.3 on 2026-03-31 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
