# Generated by Django 6.0.3 on 2026-03-31 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0008_alter_vendedor_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='negocio_pertenece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_negocio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='negocio_pertenece',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_negocio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_referir',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
