# Generated by Django 6.0.3 on 2026-03-31 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0009_area_negocio_pertenece_producto_negocio_pertenece_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendedor',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='venta',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendedor_venta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino')], default='femenino', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='referido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='salario',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
