# Generated by Django 6.0.3 on 2026-04-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0010_remove_vendedor_nombre_alter_venta_vendedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ticket_venta',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
