# Generated by Django 6.0.3 on 2026-04-03 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0011_venta_ticket_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('negocio_pertenece', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_negocio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_del_producto', to='tuKioskoApp.categoria'),
        ),
    ]
