# Generated by Django 6.0.3 on 2026-04-03 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0012_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default='Sin categoría', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_del_producto', to='tuKioskoApp.categoria'),
        ),
    ]
