# Generated by Django 6.0.3 on 2026-04-04 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0014_alter_producto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
        migrations.CreateModel(
            name='Almacenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenamiento_en_area', to='tuKioskoApp.area')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenamiento_producto', to='tuKioskoApp.producto')),
            ],
            options={
                'unique_together': {('producto', 'area')},
            },
        ),
    ]
