# Generated by Django 6.0.3 on 2026-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0015_remove_producto_cantidad_remove_producto_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='por_defecto',
            field=models.BooleanField(default=False),
        ),
    ]
