# Generated by Django 6.0.3 on 2026-04-05 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuKioskoApp', '0016_area_por_defecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nuevo Aviso', max_length=150)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Prioridad Baja'), ('media', 'Prioridad Media'), ('alta', 'Prioridad Alta')], default='baja', max_length=20)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avisos_creados', to=settings.AUTH_USER_MODEL)),
                ('visto_por', models.ManyToManyField(blank=True, related_name='avisos_leidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
